# Generated by Django 4.2.13 on 2024-06-25 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_Genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=500)),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='productos')),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.PROTECT, to='app.genero')),
            ],
        ),
    ]
